{% set version = "4.6.2" %}

package:
  name: opentrons-suite
  version: {{ version }}

source:
  url: https://github.com/Opentrons/opentrons/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 3bcc047d3e5a6e68ed2d98e2d5e477dc981fb928b39018231ba72b939b7b4876

build:
  number: 1

outputs:
  - name: opentrons_shared_data
    script: install-shared-data.bat  # [win]
    script: install-shared-data.sh  # [not win]
    build:
      noarch: python
    requirements:
      host:
        - python >=3.7
        - pip
      run:
        - python >=3.7
        - jsonschema >=3.0.2,<4.0
    test:
      imports:
        - opentrons_shared_data

  - name: opentrons
    script: install-opentrons.bat  # [win]
    script: install-opentrons.sh  # [not win]
    build:
      entry_points:
        - opentrons_simulate = opentrons.simulate:main
        - opentrons_execute = opentrons.execute:main
      skip: true  # [py<37]
    requirements:
      host:
        - python
        - pip
      run:
        - python
        - aionotify >=0.2.0  # [linux]
        - jsonschema >=3.0.2,<4.0
        - numpy >=1.15.1
        - pydantic >=1.4
        - pyserial >=3.5
        - typing-extensions >=3.7.4.3
        - {{ pin_subpackage('opentrons_shared_data', max_pin="x.x.x") }}
    test:
      imports:
        - opentrons

about:
  home: https://www.opentrons.com
  license: Apache-2.0
  license_file: LICENSE
  summary: |
    The Opentrons API is a simple framework designed to make writing automated
    biology lab protocols easy
  dev_url: https://github.com/Opentrons/opentrons
  doc_url: https://docs.opentrons.com

extra:
  recipe-maintainers:
    - mrakitin
